#!/bin/bash
set -e

# Traefik dynamic configuration generator for Authentik.
# Place this script in your Traefik folder (where docker-compose.yml lives).
# The generated config goes into the ./dynamic/ directory for file-based routing.

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
DYNAMIC_DIR="${SCRIPT_DIR}/dynamic"

echo "=== Authentik Traefik Config Generator ==="
echo ""

read -rp "Authentik domain (e.g. auth.example.de) [auth.example.de]: " AUTH_DOMAIN
AUTH_DOMAIN=${AUTH_DOMAIN:-auth.example.de}

read -rp "Authentik upstream (Docker service:port, e.g. authentik-server:9000) [authentik-server:9000]: " AUTH_UPSTREAM
AUTH_UPSTREAM=${AUTH_UPSTREAM:-authentik-server:9000}

# Create dynamic config directory if it does not exist
mkdir -p "$DYNAMIC_DIR"

CONFIG_FILE="${DYNAMIC_DIR}/authentik.yml"

# Backup existing config if present
if [[ -f "$CONFIG_FILE" ]]; then
  TS="$(date +%Y%m%d-%H%M%S)"
  BAK="${CONFIG_FILE}.bak.${TS}"
  echo ""
  echo "Existing config found. Creating backup at:"
  echo "  $BAK"
  cp "$CONFIG_FILE" "$BAK"
fi

cat > "$CONFIG_FILE" <<EOF
# Traefik dynamic configuration – Authentik reverse proxy
# Generated by generate-authentik-traefik.sh

http:
  routers:
    authentik:
      rule: "Host(\`${AUTH_DOMAIN}\`)"
      entryPoints:
        - websecure
      service: authentik
      tls:
        certResolver: letsencrypt
      middlewares:
        - security-headers

  services:
    authentik:
      loadBalancer:
        servers:
          - url: "http://${AUTH_UPSTREAM}"

  middlewares:
    security-headers:
      headers:
        stsSeconds: 3600
        contentTypeNosniff: true
        frameDeny: true
        referrerPolicy: "strict-origin-when-cross-origin"
        customResponseHeaders:
          Server: ""
EOF

echo ""
echo "Traefik dynamic config written to: ${CONFIG_FILE}"
echo "Traefik will auto-reload if file watching is enabled."
